nelmio_api_doc:
    documentation:
        info:
            title: QREDIC
            description: Evaluation des fournisseurs
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/(?!docs|admin|_(profiler|error|wdt)|login|$)
