# config/routes.yaml
app.swagger_ui:
  path: /swagger/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
# config/routes.yaml
app.swagger:
  path: /swagger/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
